name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest --verbose --cov --cov-report=xml
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: estevaofay/fast-api-poc:${{ github.run_id }}${{ github.run_number }}
  cd:
    name: Deploy Playground
    runs-on: ubuntu-latest
    needs: [ci]
    environment: dev
    steps:
      - name: Checkout ArgoCD
        uses: actions/checkout@v3
        with:
          repository: estevaofay/argocd-poc
          ref: dev
          token: ${{ secrets.PAT }}
      - name: Update Image Version
        uses: mikefarah/yq@master
        with:
          cmd: yq eval '.image.tag = "${{ github.run_id }}${{ github.run_number }}"' -i argocd-charts/charts/fast-api-poc/values.yaml
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          token: ${{ secrets.PAT }}
          commit_message: Update Tag Name
